# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r7E4iO3_V3YZLdsBc6ipxOaf160QPGq
"""

!pip install xgboost

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data

import pandas as pd

columns = ["age","workclass","fnlwgt","education","education-num","marital-status",
           "occupation","relationship","race","sex","capital-gain","capital-loss",
           "hours-per-week","native-country","income"]

df = pd.read_csv(
    "adult.data",
    names=columns,
    sep=",",
    engine="python",
    skipinitialspace=True
)

df.head()

import numpy as np

df.replace("?", np.nan, inplace=True)
df.dropna(inplace=True)

X = df.drop("income", axis=1)
y = df["income"].map({"<=50K":0, ">50K":1})

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print("Dataset ready:", X_train.shape)

from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

def evaluate_model(name, model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    return {
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "AUC": roc_auc_score(y_test, y_prob),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }

results = []

results.append(evaluate_model("Logistic Regression", LogisticRegression(max_iter=5000)))
results.append(evaluate_model("Decision Tree", DecisionTreeClassifier()))
results.append(evaluate_model("KNN", KNeighborsClassifier()))
results.append(evaluate_model("Naive Bayes", GaussianNB()))
results.append(evaluate_model("Random Forest", RandomForestClassifier()))
results.append(evaluate_model("XGBoost", XGBClassifier(use_label_encoder=False, eval_metric='logloss')))

results_df = pd.DataFrame(results)
results_df

!pip install streamlit

